from researchgraph.graph.state import ResearchState

def report_writer_node(state: ResearchState) -> dict:
    """Report writer agent to generate markdown report"""
    title = state['scope']['normalized_query']
    citation_map = state.get('citation_map', {})

    claim_lines = []

    for claim in state.get('synthesized_claims', []):
        citation_labels = [citation_map.get(source_id, source_id) for source_id in claim['supporting_source_ids']]
        suffix = ' ' + ' '.join(f'[{label}]' for label in citation_labels) if citation_labels else ''
        claim_lines.append(f"- {claim['statement']}{suffix}")

    references = []
    for source_id, label in citation_map.items():
        source = next(source for source in state['sources'] if source['source_id'] == source_id)
        references.append(f"[{label}] {source['title']}. {source['url']}.")

    markdown = '\n'.join(
        [
            f"# {title}",
            "",
            "## Executive Summary",
            "This is a stub report generated by the ResearchGraph integration graph.",
            "",
            "## Key Findings",
            *claim_lines,
            "",
            "## References",
            *references,
            "",
        ]
    )

    return {"report_markdown": markdown, "status": "exporting"}
    